# Generated by Django 6.0.4 on 2026-05-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_pdf_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
